# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: wooyeongkam/hello-world-docker-action@v9
        with:
          who-to-greet: kam
          
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

